app:
  database:
    url: ${DB_URL:jdbc:mysql://togather-database.cxs46swiy72b.ap-northeast-2.rds.amazonaws.com}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:togather1234}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:togather1234}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:togather1234}
  jwt:
    secret: ${JWT_SECRET_KEY:TogatherSecretkey}
    access-exp-seconds: ${JWT_ACCESS_EXP:1800}
    refresh-exp-days: ${JWT_REFRESH_EXP:7}
  github:
    pat: ${GH_PAT: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}