apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: ${EKS_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-gateway-discovery
  namespace: ${EKS_NAMESPACE}
rules:
  - apiGroups: [""]
    resources: ["endpoints", "services", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-discovery-binding
  namespace: ${EKS_NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: api-gateway
    namespace: ${EKS_NAMESPACE}
roleRef:
  kind: Role
  name: api-gateway-discovery
  apiGroup: rbac.authorization.k8s.io


